# Generated by Django 5.1.7 on 2025-05-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_lignefacture_prix_unitaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
