# Generated by Django 5.1.7 on 2025-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_payment_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="country_code",
            field=models.CharField(default="+216", max_length=5),
        ),
    ]
