# Generated by Django 5.1.7 on 2025-03-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_facture"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="factures/"),
        ),
    ]
