# Generated by Django 5.1.7 on 2025-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_client_country_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="stripe_payment_intent_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="paypal_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
