# Generated by Django 5.1.7 on 2025-03-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_historique"),
    ]

    operations = [
        migrations.CreateModel(
            name="LigneFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("prix_unitaire", models.DecimalField(decimal_places=3, max_digits=10)),
                ("quantite", models.IntegerField()),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=3, editable=False, max_digits=10
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="dashboard.facture",
                    ),
                ),
            ],
        ),
    ]
