# Generated by Django 5.1.7 on 2025-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="is_approved", max_length=20),
        ),
    ]
