# Generated by Django 5.1.7 on 2025-04-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_lignefacture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=10)),
                ("currency", models.CharField(default="TND", max_length=3)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("risk_level", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dashboard.facture",
                    ),
                ),
            ],
        ),
    ]
