# Generated by Django 5.1.7 on 2025-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devis",
            old_name="details",
            new_name="counter_offer",
        ),
        migrations.AddField(
            model_name="devis",
            name="counter_offer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
