# Generated by Django 5.1.7 on 2025-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(default=123456789, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devis",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("web", "Développement Web"),
                    ("mobile", "Développement Mobile"),
                    ("design", "Design Graphique"),
                    ("other", "Autre"),
                ],
                default=123456789,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="features",
            field=models.TextField(
                default=123456789,
                help_text="Liste des fonctionnalités, séparées par des virgules",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="price_range",
            field=models.CharField(
                default=123456789, help_text="Ex: 500-1000 TND", max_length=50
            ),
            preserve_default=False,
        ),
    ]
