# Generated by Django 5.1.7 on 2025-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_rename_details_devis_counter_offer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="specification_pdf",
            field=models.FileField(blank=True, null=True, upload_to="specifications/"),
        ),
    ]
