# Generated by Django 5.1.7 on 2025-04-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_client_password_devis_details_service_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_site",
                    models.CharField(
                        choices=[
                            ("vitrine", "Site Vitrine"),
                            ("ecommerce", "Site E-commerce"),
                            ("blog", "Blog"),
                            ("portfolio", "Portfolio"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fonctionnalites",
                    models.TextField(
                        blank=True,
                        help_text="Liste des fonctionnalités souhaitées, séparées par des virgules",
                    ),
                ),
                (
                    "design_personnalise",
                    models.BooleanField(
                        default=False, help_text="Design personnalisé requis ?"
                    ),
                ),
                (
                    "integration_seo",
                    models.BooleanField(
                        default=False, help_text="Intégration SEO souhaitée ?"
                    ),
                ),
                (
                    "autre_details",
                    models.TextField(
                        blank=True,
                        help_text="Autres détails ou spécifications",
                        null=True,
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produit_details",
                        to="dashboard.devis",
                    ),
                ),
            ],
        ),
    ]
