# Generated by Django 5.1.7 on 2025-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_devis_specification_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
